---
# tasks file for license scan
- name: OSS
  hosts: all
  gather_facts: no

  tasks:
  - name: Clone dpkg from git repo
    git:
      repo: git@github.com:Leoniak/dpkg-license
      version: master
      dest: /tmp/dpkg-licenses
      accept_hostkey: yes
    become: no
