---
# tasks file for license scan
- name: OSS
  hosts: all
  gather_facts: no

  tasks:
    - name: Copy dpkg-licenses to remote
      copy:
      src=/tmp/dpkg-licenses
      dest=/tmp/dpkg-licenses
