  ---
# tasks file for license scan

- hosts: all
  #remote_user: root

  tasks:
  - name: Get License of standard installed packages in RHEL
    shell: 'rpm -qa --qf "%{name}, %{version}, %{arch}, %{license} \n"'
